# Generated by Django 5.0 on 2023-12-19 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='seles',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
